import "./style.css";
import { BanyanGame, COLORS, KEYS, type BotMode, type Settings } from "./engine";

const app = document.querySelector<HTMLDivElement>("#app")!;
const SQRT3 = Math.sqrt(3);
const defaultSettings = (): Settings => ({ size: 8, players: 2, obstacles: 10, pace: .4, bots: ["human", "human", "easy", "easy", "easy", "easy"] });
let settings = { ...defaultSettings(), bots: [...defaultSettings().bots] };
let game: BanyanGame | null = null;
let screen: "home" | "custom" | "settings" | "help" | "game" = "home";
let selectedPlayer = 0;
let last = performance.now();
const audio = new Map<string, HTMLAudioElement>();
const sprites = Object.fromEntries(["Fruit", "Pest", "SquareRoot", "Player", "Land", "edge", "node"].map(name => { const image = new Image(); image.src = `/assets/${name === "Pest" ? "Pest.gif" : `${name}.png`}`; return [name, image]; })) as Record<string, HTMLImageElement>;

function sound(name: string) { const path: Record<string, string> = { fruit: "fruit_gain", capture: "capture_root", return: "fast_return", reinforce: "reinforce", win: "end_game", error: "forced_return" }; const file = path[name]; if (!file) return; let a = audio.get(file); if (!a) { a = new Audio(`/assets/${file}.ogg`); a.volume = Number(localStorage.getItem("banyan-sfx") ?? .3); audio.set(file, a); } a.currentTime = 0; a.play().catch(() => undefined); }

function setScreen(next: typeof screen) { screen = next; renderShell(); }
function button(text: string, action: string, variant = "") { return `<button class="button ${variant}" data-action="${action}">${text}</button>`; }

function renderShell() {
  if (screen === "game") { renderGame(); return; }
  const pages: Record<Exclude<typeof screen, "game">, string> = {
    home: `<main class="home"><div class="brand-mark"><span></span><span></span><span></span></div><h1>榕树之心</h1><p class="subtitle">CORE OF BANYAN</p><p class="tagline">在六边形枝网中生长、连接与守护你的根</p><div class="menu">${button("开始游戏", "new", "primary")}${button("自定义对局", "custom")}${button("新手教程", "tutorial")}${button("设置", "settings")}${button("游戏说明", "help")}</div><p class="hint">键盘 / 触屏均可操作 · 网页端复刻版</p></main>`,
    custom: customPage(), settings: settingsPage(), help: helpPage()
  };
  app.innerHTML = `${pages[screen]}<footer>Core of Banyan · Web Edition</footer>`;
  bindActions();
}
function customPage() {
  const bots = settings.bots.slice(0, settings.players).map((b, i) => `<label class="config-row"><span><i style="background:${COLORS[i]}"></i> 玩家 ${i + 1}</span><select data-bot="${i}">${(["human", "easy", "hard"] as BotMode[]).map(v => `<option value="${v}" ${b === v ? "selected" : ""}>${v === "human" ? "真人" : v === "easy" ? "简单人机" : "困难人机"}</option>`).join("")}</select></label>`).join("");
  return `<main class="panel-page"><button class="back" data-action="home">← 返回</button><h2>自定义对局</h2><p>选择一场属于你的榕树之战。</p><section class="config"><label class="config-row"><span>地图半径 <b id="size-value">${settings.size}</b></span><input id="size" type="range" min="3" max="15" value="${settings.size}"></label><label class="config-row"><span>玩家人数 <b id="players-value">${settings.players}</b></span><input id="players" type="range" min="2" max="6" value="${settings.players}"></label><label class="config-row"><span>障碍物密度 <b id="obstacles-value">${settings.obstacles}%</b></span><input id="obstacles" type="range" min="0" max="40" step="10" value="${settings.obstacles}"></label><label class="config-row"><span>移动间隔</span><select id="pace"><option value=".6">悠闲 1Hz</option><option value=".4" selected>标准 2.5Hz</option><option value=".333">迅捷 3Hz</option></select></label><div class="player-settings">${bots}</div></section><div class="actions">${button("开始生长", "start", "primary")}</div></main>`;
}
function settingsPage() { const music = localStorage.getItem("banyan-music") ?? ".5", sfx = localStorage.getItem("banyan-sfx") ?? ".3"; return `<main class="panel-page"><button class="back" data-action="home">← 返回</button><h2>设置</h2><p>声音与控制偏好会保存在本机。</p><section class="config"><label class="config-row"><span>音乐音量 <b id="music-value">${Math.round(Number(music) * 100)}%</b></span><input id="music" type="range" min="0" max="1" step=".05" value="${music}"></label><label class="config-row"><span>音效音量 <b id="sfx-value">${Math.round(Number(sfx) * 100)}%</b></span><input id="sfx" type="range" min="0" max="1" step=".05" value="${sfx}"></label></section><section class="controls"><h3>默认键位</h3><div><b>玩家 1</b><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> · <kbd>1</kbd> 回城 · <kbd>2</kbd> 加固</div><div><b>玩家 2</b><kbd>↑</kbd><kbd>←</kbd><kbd>↓</kbd><kbd>→</kbd> · <kbd>,</kbd> 回城 · <kbd>.</kbd> 加固</div></section></main>`; }
function helpPage() { return `<main class="panel-page help"><button class="back" data-action="home">← 返回</button><h2>游戏说明</h2><p>你是一颗榕树核心。移动会长出枝干；在自己的枝干上只能沿已有连接移动，枝网不能形成回路。</p><div class="rule-grid"><article><strong>创造力 E</strong><span>与树根相连的活枝越多，增长越快；攻占结点、加固枝干都会消耗它。</span></article><article><strong>坚固性 D</strong><span>每个结点有坚固性。连根时持续恢复，断根或被害虫啃食会不断流失。</span></article><article><strong>果实与害虫</strong><span>果实提供创造力，害虫会侵蚀枝干。走到其所在结点即可获得或消灭。</span></article><article><strong>落叶归根</strong><span>按回城键立即回到根，但会失去当前所在结点；加固会强化当前结点及相邻枝干。</span></article></div><div class="actions">${button("进入自定义对局", "custom", "primary")}</div></main>`; }

function renderGame() {
  app.innerHTML = `<div class="game-shell"><canvas id="board" aria-label="榕树之心游戏地图"></canvas><div class="topbar"><div class="game-title"><b>榕树之心</b><span>CORE OF BANYAN</span></div><div id="game-status" class="game-status"></div><div class="top-actions"><button class="icon-button" data-action="help">?</button><button class="icon-button" data-action="pause">Ⅱ</button></div></div><aside id="player-panel" class="player-panel"></aside><div id="toast-layer" class="toast-layer"></div><div class="mobile-controls"><button data-move="2">↖</button><button data-move="3">↗</button><button data-move="0">←</button><button data-move="1">→</button><button data-move="4">↙</button><button data-move="5">↘</button></div><div class="skill-controls"><button data-action="return"><small>1</small>落叶归根</button><button data-action="reinforce"><small>2</small>固若金汤</button></div><div id="modal" class="modal hidden"></div></div>`;
  bindActions(); bindGameInputs(); drawLoop();
}

function startGame(tutorial = false) { if (tutorial) { settings = { size: 4, players: 2, obstacles: 0, pace: .45, bots: ["human", "easy", "easy", "easy", "easy", "easy"] }; } game = new BanyanGame(settings); selectedPlayer = 0; screen = "game"; renderShell(); }
function bindActions() { app.querySelectorAll<HTMLElement>("[data-action]").forEach(el => el.addEventListener("click", () => { const action = el.dataset.action!; if (action === "home") setScreen("home"); else if (action === "new") startGame(); else if (action === "start") startGame(); else if (action === "tutorial") startGame(true); else if (action === "custom" || action === "settings" || action === "help") setScreen(action); else if (action === "pause") openPause(); else if (action === "return") game?.returnHome(selectedPlayer); else if (action === "reinforce") game?.reinforce(selectedPlayer); }));
  app.querySelectorAll<HTMLInputElement>("input[type=range]").forEach(input => input.addEventListener("input", () => { const key = input.id as "size" | "players" | "obstacles" | "music" | "sfx"; if (key === "music" || key === "sfx") { localStorage.setItem(`banyan-${key === "sfx" ? "sfx" : "music"}`, input.value); const output = document.querySelector(`#${key}-value`); if (output) output.textContent = `${Math.round(Number(input.value) * 100)}%`; } else { settings[key] = Number(input.value); const out = document.querySelector(`#${key}-value`); if (out) out.textContent = `${input.value}${key === "obstacles" ? "%" : ""}`; if (key === "players") { const p = document.querySelector(".player-settings"); if (p) p.innerHTML = settings.bots.slice(0, settings.players).map((b, i) => `<label class="config-row"><span><i style="background:${COLORS[i]}"></i> 玩家 ${i + 1}</span><select data-bot="${i}">${(["human", "easy", "hard"] as BotMode[]).map(v => `<option value="${v}" ${b === v ? "selected" : ""}>${v === "human" ? "真人" : v === "easy" ? "简单人机" : "困难人机"}</option>`).join("")}</select></label>`).join(""); bindBotSelects(); } } }));
  document.querySelector<HTMLSelectElement>("#pace")?.addEventListener("change", e => { settings.pace = Number((e.target as HTMLSelectElement).value); }); bindBotSelects();
}
function bindBotSelects() { app.querySelectorAll<HTMLSelectElement>("[data-bot]").forEach(s => s.addEventListener("change", () => { settings.bots[Number(s.dataset.bot)] = s.value as BotMode; })); }
function bindGameInputs() { window.onkeydown = e => { if (!game || screen !== "game") return; const key = e.key.toLowerCase(); if (key === "escape") { openPause(); return; } if (key === "1") game.returnHome(selectedPlayer); if (key === "2") game.reinforce(selectedPlayer); for (let player = 0; player < Math.min(4, game.players.length); player++) { const direction = KEYS[player].indexOf(key); if (direction >= 0 && settings.bots[player] === "human") { selectedPlayer = player; game.move(player, direction); e.preventDefault(); } } };
  app.querySelectorAll<HTMLElement>("[data-move]").forEach(b => b.addEventListener("click", () => game?.move(selectedPlayer, Number(b.dataset.move))));
}
function openPause() { const modal = document.querySelector<HTMLDivElement>("#modal"); if (!modal) return; modal.classList.remove("hidden"); modal.innerHTML = `<section><p class="eyebrow">游戏暂停</p><h2>枝干会在此刻静止</h2><div class="modal-actions">${button("继续生长", "resume", "primary")}${button("重新开始", "restart")}${button("回到主页", "quit")}</div></section>`; modal.querySelectorAll<HTMLElement>("[data-action]").forEach(b => b.addEventListener("click", () => { const a = b.dataset.action; if (a === "resume") modal.classList.add("hidden"); if (a === "restart") { game?.reset(); modal.classList.add("hidden"); } if (a === "quit") { game = null; setScreen("home"); } })); }

function drawLoop(now = performance.now()) { if (screen !== "game" || !game) return; const delta = (now - last) / 1000; last = now; const modal = document.querySelector("#modal"); if (modal?.classList.contains("hidden")) game.update(delta); drawBoard(); updateHud(); requestAnimationFrame(drawLoop); }
function drawBoard() {
  const canvas = document.querySelector<HTMLCanvasElement>("#board")!; const rect = canvas.getBoundingClientRect(); const ratio = Math.min(devicePixelRatio, 2); const w = Math.floor(rect.width * ratio), h = Math.floor(rect.height * ratio); if (canvas.width !== w || canvas.height !== h) { canvas.width = w; canvas.height = h; } const ctx = canvas.getContext("2d")!; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); ctx.clearRect(0, 0, rect.width, rect.height); const g = game!; const n = g.settings.size - 1; const scale = Math.min(rect.width / (2 * n + 3), rect.height / (SQRT3 * n + 3)) * .92; const cx = rect.width / 2, cy = rect.height / 2 + 22;
  const pos = (x: number, y: number) => { const p = g.world({ x, y }); return { x: cx + (p.x - n) * scale, y: cy + p.y * scale }; };
  const gradient = ctx.createRadialGradient(cx, cy, 20, cx, cy, Math.max(rect.width, rect.height) * .7); gradient.addColorStop(0, "#16365a"); gradient.addColorStop(1, "#061020"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, rect.width, rect.height);
  ctx.lineCap = "round";
  for (const c of g.cells.values()) { if (c.owner < 0) continue; const a = pos(c.x, c.y); for (const e of c.edges) { const [one, two] = e.split("|"); if (one !== `${c.x}:${c.y}`) continue; const [x, y] = two.split(":").map(Number); const b = pos(x, y); ctx.strokeStyle = COLORS[c.owner]; ctx.globalAlpha = .72; ctx.lineWidth = Math.max(3, scale * .13); ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); } }
  ctx.globalAlpha = 1;
  for (const c of g.cells.values()) { const p = pos(c.x, c.y), r = scale * .30; if (c.wall) { ctx.fillStyle = "#1c2e46"; hex(ctx, p.x, p.y, r); ctx.fill(); continue; } ctx.fillStyle = c.owner >= 0 ? COLORS[c.owner] : "#dce8ec"; ctx.globalAlpha = c.owner >= 0 ? .95 : .25; hex(ctx, p.x, p.y, r); ctx.fill(); ctx.globalAlpha = 1; ctx.strokeStyle = "rgba(255,255,255,.25)"; ctx.lineWidth = 1; hex(ctx, p.x, p.y, r); ctx.stroke(); if (c.owner >= 0) { ctx.fillStyle = "#071326"; ctx.font = `600 ${Math.max(10, scale * .18)}px Banyan`; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(String(Math.floor(c.hp)), p.x, p.y + 1); } if (c.root) { ctx.drawImage(sprites.SquareRoot, p.x - r * .55, p.y - r * .49, r * 1.1, r * .95); } if (c.fruit > 0) { ctx.drawImage(sprites.Fruit, p.x - r * .34, p.y - r * 1.58, r * .68, r * .68); } if (c.pest) { ctx.drawImage(sprites.Pest, p.x - r * .68, p.y - r * 1.45, r * 1.36, r * .72); } }
  for (const p of g.players.filter(p => p.alive)) { const at = pos(p.x, p.y), r = scale * .34; ctx.save(); ctx.globalCompositeOperation = "source-over"; ctx.drawImage(sprites.Player, at.x - r, at.y - r, r * 2, r * 2); ctx.globalCompositeOperation = "source-atop"; ctx.fillStyle = COLORS[p.id]; ctx.globalAlpha = .65; ctx.fillRect(at.x - r, at.y - r, r * 2, r * 2); ctx.restore(); ctx.strokeStyle = "#fff"; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.arc(at.x, at.y, r * .52, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = "#fff"; ctx.font = `800 ${Math.max(10, scale * .16)}px Banyan`; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(String(p.id + 1), at.x, at.y + 1); }
}
function hex(ctx: CanvasRenderingContext2D, x: number, y: number, r: number) { ctx.beginPath(); for (let i = 0; i < 6; i++) { const a = Math.PI / 6 + i * Math.PI / 3; const px = x + Math.cos(a) * r, py = y + Math.sin(a) * r; if (i) ctx.lineTo(px, py); else ctx.moveTo(px, py); } ctx.closePath(); }
function updateHud() { const g = game; if (!g) return; const panel = document.querySelector("#player-panel"); const status = document.querySelector("#game-status"); if (!panel || !status) return; panel.innerHTML = g.players.filter(p => p.alive).map(p => `<button class="player-card ${p.id === selectedPlayer ? "selected" : ""}" data-player="${p.id}"><i style="background:${COLORS[p.id]}"></i><span>玩家 ${p.id + 1}${settings.bots[p.id] !== "human" ? " · AI" : ""}</span><b>${Math.floor(p.energy)} E</b></button>`).join(""); panel.querySelectorAll<HTMLElement>("[data-player]").forEach(b => b.onclick = () => selectedPlayer = Number(b.dataset.player)); const alive = g.players.filter(p => p.alive).length; status.innerHTML = `<span>${Math.floor(g.elapsed / 60).toString().padStart(2, "0")}:${Math.floor(g.elapsed % 60).toString().padStart(2, "0")}</span><span>${alive} 棵榕树</span>`; for (const e of g.consumeEvents()) { toast(e.text, e.kind); sound(e.kind); } if (g.ended) showWin(g.winner); }
function toast(text: string, kind: string) { const layer = document.querySelector("#toast-layer"); if (!layer) return; const el = document.createElement("div"); el.className = `toast ${kind}`; el.textContent = text; layer.append(el); setTimeout(() => el.remove(), 2000); }
function showWin(winner: number) { const modal = document.querySelector<HTMLDivElement>("#modal"); if (!modal || !modal.classList.contains("hidden")) return; modal.classList.remove("hidden"); modal.innerHTML = `<section><p class="eyebrow">对局结束</p><h2>玩家 ${winner + 1} 守住了榕树之心</h2><p>最后一棵仍扎根于大地的榕树获得胜利。</p><div class="modal-actions">${button("再来一局", "restart", "primary")}${button("回到主页", "quit")}</div></section>`; modal.querySelectorAll<HTMLElement>("[data-action]").forEach(b => b.addEventListener("click", () => { if (b.dataset.action === "restart") { game?.reset(); modal.classList.add("hidden"); } if (b.dataset.action === "quit") { game = null; setScreen("home"); } })); }

renderShell();
